// app/layout.js

import { Inter } from "next/font/google";
import "./globals.css";
import ClientAnalytics from "../components/ClientAnalytics";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Coffee Shop - AI Customer Care",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientAnalytics />
        {children}
      </body>
    </html>
  );
}
